### ISSUE TITLE
`enabled` option of cramToFastq doesn't work as expected

### ISSUE THREAD

**Issue by cakirb** [cellgeni/nf-irods-to-fastq#2]
I've tried to modify `enabled` part as `"${params.publish_fastqs} && ${!params.for_upload} == true"` on my side, but it doesn't fix the issue even the expression should return true

**Comment by prete** [comment]
Part of this was sorted at: 7585d718136816d57db946bca5446be893cce3bf
Now you can have the functionality expressing both publish and merge with:
```
nextflow run main.nf \
        --meta samples.csv \
        --publish_fastqs \
        --merge \
        -resume
```

Haven't tested automatic upload yet.
